.gitignore, Dockerfile, Pipfile, Pipfile.lock, basic/settings.py, buildspec.yml, docker-entrypoint.sh, hedera_nginx.conf
This PR introduces the following changes that enable a deployment to a development environment on AWS:
- A ./Dockerfile containing instructions to build the application and bundle it in a docker image
- A ./buildspec.yml file that triggers the aforementioned Dockerfile instructions
- A ./hedera_nginx.conf that configures nginx for the app
- A ./docker-entrypoint.sh file that runs nginx and gunicorn so that the application can be served up
An infrastructure setup of this project is to be found at https://github.com/Hedera-Lang-Learn/hedera-terraform/tree/aws-codepipeline-ecs-IaC. Thus, a quick way to test the changes introduced in this PR would be to run the `terraform [command]` commands in the aforementioned repo. That repo contains a CodeBuild and CodePipeline that will engage all the …
=> Code to enable deployment to a remote development environment on AWS

README.md
It's slightly easier to do `runserver` in the same window as you already have `pipenv shell` running.
Not a big deal but it saves a line :-)
=> swapped around terminal instructions in README

docker-entrypoint-dev.sh, docker-entrypoint-prod.sh
DATABASE_URL is used in place the canonical django database env variables, e.g. DB_NAME, DB_HOST, etc, for specifying a database backend.
See https://github.com/kennethreitz/dj-database-url for reference.
=> Use dj_database_url for db backend config

hedera/settings.py
Adding a DEFAULT_FROM_EMAIL directive in the settings module that specifies the default email sending address. This is to be populated by an environment variable of the same name.
=> Add DEFAULT_FROM_EMAIL env var

hedera/settings.py
Not sure why this was commented out but this avoids real email from trying to be sent during local development.
=> Run with console email backend by default to make local dev easy

hedera/templates/lemmatized_text/create.html, lemmatization/lemmatizer.py, lemmatization/services/clancydb.py, lemmatization/services/morpheus.py
First pass at updating `lemmatize_word()` to support russian word forms by calling out to a service that I've dubbed `clancydb` (named for Steven Clancy who created the database).
Since we'd like to be able to support other languages too, rather than hard-coding the method call,  I've created a mapping of each language code to a module capable of lemmatizing that language. The only requirement is that the module implements a `lemmatize_word(form, lang)` function and declares a service identifier (SID). 
This structure should make it possible to add other languages in a straightforward manner. A module could support one language like `clancydb` or multiple languages like `morpheus`.
=> Russian Lemmatizer

lemmatization/lemmatizer.py, lemmatization/services/base.py, lemmatization/services/clancydb.py, lemmatization/services/morpheus.py, lemmatized_text/models.py
When pulling out tokenization I noticed there was a token stripping line that seemed like it might be language specific so I pulled that out as well.  That led me down the path of refactoring all the common factors between the two services into a base class which keeps the service implementations focused.
Local smoke testing seems to pass for me but probably best if @arthurian could review my changes.
Refs #76
=> Refactor services extracting tokenizations/stripping

Pipfile, Pipfile.lock, docker-entrypoint-webserver-dev.sh, docker-entrypoint-webserver-prod.sh, hedera/settings.py
This PR configures [sentry](https://sentry.io/) for error tracking on the backend. 
Note that for local testing, it's OK to leave the `SENTRY_DNS` undefined. In that case, no events will be sent and any calls to the sentry SDK will become no-ops. If a `SENTRY_DNS` is defined,  any events from localhost will be ignored by sentry.io (configured via admin settings). All other events should be tagged with an environment via `SENTRY_ENVIRONMENT` for easy filtering (e.g. _dev_ or _prod_).
=> Configure sentry for error tracking on the backend

hedera/settings.py, hedera/urls.py, import-data/clancy-russian.tsv, lemmatization/lemmatizer.py, lemmatization/services/base.py, lemmatization/services/clancy.py, load_clancy_lattice.py
First pass at fixing the russian lemmatization (without breaking latin/greek).
- ~~Uncommented the lattice/lemma node creation that was previously commented out during the most recent revisions.~~
- Created data load for russian similar to Logeion `clancy-russian.tsv`.
- Ensured that the proper `context` (e.g. `morpheus` or `clancy`) is passed when creating lattice/lemma nodes.
- Tweaked the logging config slightly for debugging and enabled the `django-rq` admin links to view job status.
=> Fix russian lemmatization

static/src/js/app/components/vocab-list-select/VocabListSelectedEntry.vue, static/src/js/app/vuex/getters.js
Pull request #161 was the one introducing a second visualization to display weighted percentage of known words. The reason for undoing the pull request is that the changes introduced seem to be the cause of the browser-page-freeze that happens when you click the vocab list dropdown and select a vocab list. The reason for the freeze is likely that the changes introduced in the pull request are a bit heavy to run on the front-end. I noticed that when you open the Chrome Task Manager and select a vocab list, the CPU usage spikes to 100+ and stays as such indefinitely. Thus, perhaps the computation introduced in the PR is heavy for running on the front-end or there is a bug in the code change in that PR. The real reason is yet TBD. At any rate, reverting the pull request resolves the problem. …
=> Revert pull request #161 to fix freezing-page problem

static/src/js/app/components/vocab-list-select/VocabListSelectedEntry.vue, static/src/js/app/vuex/getters.js
The weighted percentage chart was removed for the reason explained in https://github.com/Hedera-Lang-Learn/hedera/pull/175
The bug was that the loop variables of the for-loops were not incrementing, thereby causing infinite loops.
This PR returns the weighted percentage chart while fixing the for-loop constructs to get rid of the bug.
=> Restore weighted percentage chart with bugfix

hedera/templates/site_base.html
This PR updates the [Noto](https://www.google.com/get/noto/) font definition so that russian text, particularly accented text, is rendered correctly. 
Example before and after: 
(Edited per discussion below)
=> Customize font for reading

lemmatization/lemmatizer.py, lemmatization/services/base.py, lemmatization/tokenizer.py
This is a proposed change to (a) allow for more language-specific tokenization rules and (b) allow for words to be matched against a normalized form. It includes a minimal proof of concept for russian that handles accented text and common hyphenated words that should not be split.
The tokenized response includes both the original word and a normalized form for internal matching as suggested in #137. For latin/greek it currently returns the word as-is.
```
(word, following) => (word, normalized, following)
```
Thoughts?
=> Proposed: tokenization updates to allow for language-specific rules

hedera/api.py, static/src/js/app/App.vue, static/src/js/app/Learner.vue, static/src/js/app/modules/LatticeNode.vue, static/src/js/app/modules/LatticeTree.vue, static/src/js/app/modules/LemmatizedText.vue, static/src/js/app/modules/MarkResolved.vue, static/src/js/app/modules/Token.vue, static/src/js/app/vuex/actions.js, static/src/js/app/vuex/getters.js, static/src/js/app/vuex/mutations.js, static/src/js/app/vuex/state.js
You can now select "Apply All" after marking a token as resolved if there are other matching tokens in the text to apply the same disambiguation to them in one go.
@jtauber Could you do a review of this for me.  There is a lot of changes to support this that could impact a lot of things.  I have tested it locally and fixed what I've found except for "Add a Lemma".  That's not working but when I went to troubleshoot it I don't see how it could possibly be working currently as the I don't see in the API handler where the data is being handled.  
I'll verify if this is indeed a regression or not later, but wanted to get this PR up and ready for review.  Regression or not, we need to fix the the ability to add a lemma but might not need to hold up this merge.
=> Bulk disambiguation

fixtures/flatpages.json, hedera/settings.py, hedera/templates/flatpages/default.html, hedera/templates/site_base.html, hedera/urls.py, static/src/scss/_body.scss
* adds a top level nav link, "About" to `/about/`
* adds a flat pages app to Django admin, where you can create pages at any URL not already being used by the application
* renders content into a template with a left hand nav column that will auto generate links based on the pages you create
* comes with a fixture to create the first two pages for you that you can edit (after deploy run `./manage.py loaddata flatpages`
* The top level `/about/` is hard coded so you'll need to at least have that flatpage.  If you change the url in the `/about/` fixture, we'll need to change the url in the template for the navbar.
--
Ref #184
=> Add flatpages for staff maintained content

docker-entrypoint-webserver-prod.sh, hedera/settings.py
This PR fixes django DEBUG so that is actually False in prod, as expected.
When you pass in 'False' into the 'DJANGO_DEBUG' env var, it is parsed as a True-ey string in settings.py, which is not what we want. Instead of 'False', set the DJANGO_DEBUG env var to 0. It is still a string, but it is Falsy.
=> Fix django debug

hedera/settings.py
This PR fixes ALLOWED_HOSTS for subdomains so that dev.hederaproject.org can work without throwing an error.
=> Fix django ALLOWED_HOSTS for subdomains

hedera/api.py, lemmatized_text/views.py, setup.cfg
This was an issue reported via email where when a student clicked on a text from a class they received a 404
=> Let learner see and set familiarity with text in class

Dockerfile
`awscli` was used to run AWS CLI commands in the docker entrypoint scripts. The commands were for reading environment variable values from the AWS Systems Manager Parameter Store. However, we moved that functionality [into the ECS Task Definition](https://github.com/Harvard-ATG/atg-ops-ecs/blob/master/terraform/dev/nonlti-hedera/container-definitions.json). And so we no longer need the awscli package.
I have tested the change. All good.
=> Remove installation of awscli

Dockerfile
This PR simply updates the base image in the Dockerfile.
[The previous image](https://hub.docker.com/layers/circleci/python/3.7-rc-node/images/sha256-26b8a94f14ef32bba65e8d6ebb8363a617bc9e37d156139ae3e9abf960b50af1?context=explore) has not been updated in 2 years, and so the Dockerfile's build step was failing on account of node being out of date.
[The new image](https://hub.docker.com/layers/circleci/python/3.7-node/images/sha256-ae3a9bf963311574da177ba09a552aff95586555c0a275c8757a299bcaca055a?context=explore), on the other hand, is getting updated. For instance, the latest update is as of 17 hours ago at the time of this writing.
=> Update base image in Dockerfile

README.md, hedera/settings.py, hedera/templates/lemmatized_text/create.html, lemmatization/lemmatizer.py, lemmatization/tokenizer.py, lemmatized_text/models.py
Primarily:
* implements `|` and `_` as a way of overriding tokenization (`|` splits a word into two tokens, `_` joins two words as a single token)
* if a multi-word token has a form of to be (from Ivy's list) only the other word is used for lemmatization
* clone `original_text` not tokenized `text` so above is not lost
This addresses #57 
Also:
* allow `LemmatizedText.cloned_for` to be blank in admin (couldn't edit `LemmatizedText` in admin otherwise)
* from upstream: disable SESSION_COOKIE_SECURE in local dev
* fixed typo in README
=> Enclitic tokenization

.pre-commit-config.yaml
Quick fix for flake8
- flake8 is not picking up the configuration setting for `inline-quotes = 'double'` so I added it in the args field in pre-commit-config.yaml
=> fix flake8 precommit to check double quotes

package-lock.json, package.json, static/src/js/app/PersonalVocab.vue, static/src/js/app/index.js
This PR fixes slow render performance of the personal vocab when there are a lot of entries.
Changes:
- Added [vue-good-table](https://xaksis.github.io/vue-good-table/) component to render the personal vocab entries.
- Enabled [pagination](https://xaksis.github.io/vue-good-table/guide/configuration/pagination-options.html#enabled) and [searching](https://xaksis.github.io/vue-good-table/guide/configuration/search-options.html) of the entries. 
Notes:
- Since the API query returns quickly and is not currently a bottleneck, we're not paginating that yet. The `vue-good-table` component supports server-side pagination, so we can implement that when needed.
Example screenshot:
=> Paginate personal vocab entries

vocab_list/models.py, vocab_list/tests.py
This PR resolves [ATGU-3255](https://jira.huit.harvard.edu/browse/ATGU-3255) by:
- Adding the `AbstractVocabList` and `AbstractVocabListEntry` abstract classes to refactor repeated fields and methods
- Adding tests to gauge the safety of the refactoring/absracting 
- Adding docstrings to functions/methods that could use some documentation
- The refactoring/abstraction definitely helps this module to adhere to DRY principals, but I wonder if it makes it more or less comprehensible? That's an open question for me
=> Vocab list refactor

.dockerignore, .github/workflows/ci.yaml, .gitignore, README.md, docker-compose.yml, hedera/settings.py, hedera/test_settings.py, hedera/tests/test_api.py
Provides instructions for running unit tests locally, and adds them to CI in a separate job (it will run in parallel with the build and code quality test job).
To get tests to work, we had to ensure that local and containerized test runs have access to postgres and redis, and that the tags in our templates provided by django-webpack-loader will not result in errors at test time if webpack hasn't actually been run to build static assets. This means that the webpages rendered by Django in unit tests do not have the real JS resources in them, so this approach isn't appropriate for end-to-end testing / UI interactions, but is quicker and more focused than also having to build and serve the webpack assets for each test run.
Steps to run tests are outlined in the README.md, but to summarize: …
=> Run python unit tests in CI

lemmatized_text/views.py
This PR resolves [ATGU-3377](https://jira.huit.harvard.edu/browse/ATGU-3377) by:
- Making sure sub queryset contains only unique lemmatized text objects
The filter queryset was sometimes returning the same text many times, so when `get_object_or_404` was called on that queryset with pk as the identifier, it was producing a "too many objects returned" error, as it expects only  a single text to be returned.
=> Fix multiple obects returned error on lemmatized_text view

.dockerignore, Dockerfile, Dockerfile.dev, README.md, docker-compose-common.yml, docker-compose.yml
This is a PR to spark some discussion. 
For easier debugging in local development, one approach is to ~use a dev Docker image that includes dev requirements~ make use of a multistage build, where dev requirements are extra layers on top of the production image.
Pros:
- prod image can also be run locally (e.g. for `npm` service)
- dev image "tests" prod image by inheriting from it
Cons:
- when running prod image, need to target the `prod` build stage explicitly to avoid including `dev` layers.
=> Use multistage build to help with local dev

docker-compose-common.yml, docker-compose.yml, package-lock.json, static/src/js/app/api.js, static/src/js/app/components/quick-add-button/QuickAddVocabForm.vue, static/src/js/app/vuex/actions.js
- removed blocking code from quick add component so other languages can lookup headwords
- Added extra parameter when looking up headwords
Note: as of right now there is no way to distinguish/match languages between glosses that is returned. Chinese is the only language that can be matched via context on the lattice node. However Russian, and Latin context are referenced with `Clancy` and `Morpheus` respectively. We would need a way to validate that the actual gloss thats returned is for the correct language.(I am not sure about Greek since there doesn't seem to be a script to load that lattice in)
=> Fix quick add suggested gloss so other languages can lookup headwords

lemmatization/lemmatizer.py, lemmatization/services/latin.py, lemmatized_text/models.py
This PR updates the latin`latin_periphrastic_normalizer` to strip the macrons out of the lemmas when new text is parsed. This is related to the subsequent schema redesign.
=> dojo changes from 8-9-22

lemmatization/admin.py, lemmatization/lemmatizer.py, lemmatization/models.py, lemmatization/services/latin.py
This PR is the result of a coding session with @bilbe @Tanvez and @arthurian. The primary goal of the session was to update the lemmatizaton process for latin to handle words with macrons such that if `hīc` appears in a text, it can be lemmatized as `hic2` immediately. The default case is that `hic` is lemmatized and returns two options: `hic1` and `hic2`. While we can't say for certain which one is meant for `hic`, we know that `hīc` always means `hic2`.
Changes:
- Updated `latin.py` lemmatizer so that if a macron is detected in a word, perform a form2lemma lookup immediately and use the result if it's found, otherwise fallback to looking up the normalized word. We tested this and it appears to be working as expected, once we added an entry in the form2lemma table for `hīc -> hic2`.
- …
=> Hedera Dojo 2022-08-18

lemmatization/tests/test_lemmatizers.py, lemmatized_text/models.py, lemmatized_text/tests.py
This PR fixes the failing lemmatization unit tests.
* Removed `LatinLexicon` model since we are no longer using it.
* Fixed Lemmatization unit tests.
* Fixed LemmatizedText unit tests.
Notes:
* We need a better way of handling html unit tests. String comparisons are brittle!
=> Fix failing lemmatization tests

hedera/supported_languages.py, lemmatization/lemmatizer.py, lemmatization/services/base.py, lemmatization/services/chinese.py, lemmatization/services/greek.py, lemmatization/services/latin.py, lemmatization/services/russian.py, lemmatization/tests/test_data.py, lemmatization/tests/test_preprocessors.py, static/src/js/app/modules/FormDisambiguation.vue, static/src/js/app/modules/LemmatizedText.vue
This PR adds the following:
- A preprocessor class to `base.py` and `lemmatizer.py` to further parse out enclitics from an already tokenized words in a latin text. Note: Placeholder methods are created for other languages(chinese, russian, and greek)
- Test for the latin preprocessor
- Changes were made to the front-end to account for words lookup_form that includes macrons
=> Refactor lemmatizer enclitics

docker-compose.yml, hedera/api.py, hedera/templates/lemmatized_text/handout.html, hedera/tests/test_api.py, hedera/urls.py, lemmatization/models.py, lemmatized_text/models.py, lemmatized_text/views.py
This PR adds the `pdf-service` to docker, which is required to generate a handout in the learner view, and fixes the handout using the new models. Note that this piece can probably be replaced with a simpler method of generating PDFs, but for now just trying to align with what is running in dev/prod.
=> Add pdf-service to docker compose and fix handout

lemmatized_text/parsers.py
This should fix an error where edited texts do not appear after editing them, because the parser expects node attributes on words in the text
=> fix editing lemmatized texts

hedera/api.py, lemmatization/services/base.py, lemmatization/services/latin.py, static/src/js/app/api.js, static/src/js/app/components/quick-add-button/QuickAddVocabForm.vue, static/src/js/app/vuex/actions.js, vocab_list/models.py
This commit fixes the quick add component to work without the lattice. Quick add prompts users for a headword and definition, and as they type the headword, a set of radio button options appears with lemmas to connect to. The selected lemma is linked to the vocab list entry when it is added to the list.
This commit also makes some changes to the api and models in django. This improves error logging on the quick add endpoint and fixes an error that would occur when the `data` method was called on vocab list entries that didn't have an associated lemma.
=> fix quick add

README.md
Adds `--service-ports` to `docker compose run` command for django unit tests so that debugger port is exposed for debug client connections.
During the 10/25/2022 `#dojo` session we ran into a problem with local debug config that prevented connecting the VS Code debugger (client) to the `debugpy` server running in the app under test.
This appears to have been due to this quirk of the `run` command:
> The second difference is that the `docker compose run` command does not create any of the ports specified in the service configuration. This prevents port collisions with already-open ports. If you do want the service’s ports to be created and mapped to the host, specify the `--service-ports`
> (cf https://docs.docker.com/engine/reference/commandline/compose_run/#description)
=> (docs) Fix example for running local tests

static/src/js/app/vuex/actions.js
This PR fixes the text learner view familiarity interaction. When changing a familiarity rating for new words that are not included in the users personal vocabulary list the UI would not update the ratings for the newly changed/added word when navigating away and back to the previously changed/added word.
Note: the updated code is very similar to how `UPDATE_VOCAB_ENTRY` actions is interacting with the `updatePersonalVocabList` api. We will need to optimize the code to conform to DRY principles
=> Fix familiarity in learner view

static/src/js/app/Learner.vue
This PR updates the learner view of the selected word so that the dictionary entry is always displayed, and only the gloss is hidden by default.
**Default view when clicking on a word in the text:**
**With the gloss revealed:**
=> Learner Selected Word Reveal Gloss

hedera/api.py
This bug occurs when text is edited. The new tokens don't have "resolved" `key:value` pair in the newly created dict. This would throw a key error.
- Added conditional to check if dict has "resolved" key and default value for "resolved" since it is used for comparison further down in the code.
The newly calculated percentage don't match because of another bug where edited text have extra blank tokens
=> fix key error in API when edit happens

static/src/js/tests/VocabGeneral.spec.js, static/src/js/tests/VocabPersonal.spec.js
This PR fixes the jest test vue warning message: `[Vue warn]: Unknown custom element: <b-form-input> - did you register the component correctly? For recursive components, make sure to provide the "name" option.`
- Added bootstrapvue plugin as an import/plugin in `VocabGeneral` and `VocabPersonal` test specs
=> fix unknown custom element in jest test

hedera/requirements/base.in, hedera/requirements/base.txt, lemmatization/tests/test_lemmatizers.py, lemmatization/tests/test_tokenizers.py
For some reason, the Python tests have started failing in GitHub actions. A failing run with logs can be seen here: https://github.com/Hedera-Lang-Learn/hedera/actions/runs/3603801082/jobs/6073350159. The issue seems to be with setting up `paddle`, which is being installed because of `lac`, which is part of the lemmatizer for Chinese language text. Since we've removed Chinese language support from the app for the time being, this PR removes `lac` from the requirements and comments out the tests that depend on it. The library and tests should be reinstated as part of bringing Chinese language support back in to the app, when that happens.
=> Fix failing python tests

static/src/js/app/api.js, static/src/js/app/vuex/actions.js, static/src/js/app/vuex/tests/actions.spec.js
This PR makes any action that makes an api call into an `async` function that `await`s the response from the api, rather than relying on passing callbacks through to the api calls.
It also revamps the actions test suite to ensure that the API is being called with the expected parameters, mock out axios calls to the api to simulate a returned data object, and ensure that the mutation in the action is also called with the expected parameters. The first test in the suite has extra documentation to use as a reference implementation for adding additional action tests beyond the 5 that are currently implemented.
=> Make actions use async

.pre-commit-config.yaml, Dockerfile
This PR updates the `DockerFile` and `pre-commit-config.yaml` Python version from 3.7 to 3.10([Django 3.2 Supported](https://docs.djangoproject.com/en/4.1/releases/3.2/#python-compatibility)). 
Resolves #492
=> updated python version from 3.7 to 3.10

hedera/templates/_account_bar.html, static/src/js/app/Dashboard.vue, static/src/js/app/api.js, static/src/js/app/components/quick-add-button/QuickAddVocabForm.vue, static/src/js/app/constants.js, static/src/js/app/index.js
This PR fixes a bug where quick add would not load in dashboard and navbar due to undefined variable `this.vocabListType` and failing submit for personal vocab list from quick add modal
- Added secondary condition to default to personal vocab  if `this.vocabListType` is null
- Fix constant name/action for `vocabularyListEntry_create`
- Added `isPersonal` variables to dashboard and navbar to default to personal vocab list in the quick add modal
- Fix quick add for personal vocab list
=> Fix bug where quick add would not load in dashboard and navbar

lemmatization/services/base.py, lemmatization/services/latin.py, lemmatized_text/models.py, lemmatized_text/parsers.py, lemmatized_text/test_data.py, lemmatized_text/tests.py
This PR is to fix issue #500 where latin text edited with underscores will not be picked up by the editor.
- added `check_text` and `apply_text_rule ` to latin service to be used in the `parsers.py` to determine underscores in a text
- added test for edits with underscore
=> fix underscore

lemmatized_text/parsers.py
This PR fixes the failing edits when unedited text is submitted to the edit endpoint.
- Added a check for length of the new_data due to error `list index out of range` when accessing array elements in `parsers.py`
=> fix failing editor when unedited text are submitted

README.md, hedera/templates/site_base.html
This PR fixes the missing icons in the personal vocabulary page.
- Updated the fontawesome kit link
- Added under the `gotchas` section of the readme noting the setup for fontawesome kit link
Note: we can download the `js` file into the repo as well, and not rely on the link. Will hold off until further review.
=> fix missing icons due to fontawesome kit expire

.github/workflows/ci.yaml
This PR updates Github Actions [setup-python](https://github.com/actions/setup-python) to use python 3.10, which matches the deployed version in the `Dockerfile.`
=> Updated github actions to use python 3.10

static/src/js/app/Dashboard.vue
This PR fixes an error where lang is undefined when `Dashboard.vue` is loaded.
=> fixing undefined lang when loading vue dashboard

hedera/settings.py, hedera/urls.py, web-entrypoint.sh, webpack.config.js
This PR adds sentry to frontend and backend.
- atg-ops-ecs has been updated to pull in sentry-auth-token
- added an endpoint to trigger via sentry-debug
- added sentry-auth-token into the ssm param store
=> Add sentry

hedera/templates/lemmatized_text/learner_text.html, hedera/templates/lemmatized_text/text.html, static/src/scss/_text.scss
Fix breadcrumbs in django templates to navigate to previous page instead of lemmatized text and changed the `<b/>` to `<h1/>`
Note:  I have left the a tag name as `Lemmatized Texts`. Feel free to comment on how we should change the naming convention to either `back` or `previous`
=> Update breadcrumbs/title in django template
