Hedera-Lang-Learn/hedera

fixtures/sites.json

Change top-level domain in the sites fixture from .com to .org.

Update the top-level domain in the sites fixture

---

Pipfile
Pipfile.lock
hedera/api.py
hedera/settings.py
lattices/models.py

Includes all parents as well as single child descendants in the lattice for vocab list matching.

Highlight related nodes

---

README.md
lattices/utils.py
lemmatization/lemmatizer.py
static/src/js/app/modules/LatticeNode.vue

* in README, discourage loading of fixtures to get lattice and lemmatisation info (they should be imported via code not fixtures)
* fix bug where duplicate parent lemmas were creating for lemmas ending in numbers
* label the form nodes "ambiguous X" rather than "form X" to make clearer they are only representing ambiguities in lemma (which is why they are parents, not children of lemmas)
* strip punctuation in naming form nodes
* hand em-dashes better (workaround for #36)

Lattice improvements

---

.gitignore
Pipfile
Pipfile.lock
hedera/templates/lemmatized_text/create.html
hedera/templates/vocab_list/list.html
hedera/templates/vocab_list/personal.html
package-lock.json
package.json
vocab_list/models.py

Jus made a few cosmetic and functional changes.

Bills branch

---

hedera/api.py
hedera/templates/lemmatized_text/list.html
hedera/templates/site_base.html

Add link to personal vocab list at top nav

---

static/src/js/app/vuex/actions.js

Fix issue where api changed

---

vocab_list/models.py

Fix personal vocab import

---

static/src/js/app/vuex/getters.js

Do not include tokens that won't be resolved in total count

---

hedera/templates/vocab_list/delete.html
hedera/templates/vocab_list/list.html
vocab_list/urls.py
vocab_list/views.py

Add the ability to delete vocab lists

---

vocab_list/models.py
vocab_list/views.py

It was just a couple little things but it caused errors when uploading vocab lists.

Fixed Sentry errors found when uploading vocab lists.

---

static/src/js/app/components/vocab-list-select/VocabListSelect.vue
static/src/js/app/components/vocab-list-select/VocabListSelectedEntry.vue
static/src/js/app/vuex/getters.js

This PR introduces a getter method for computing weighted percentage of known words. Also, visually, an extra chart is displayed right below the one that shows raw percentage.

Weighted percentage of known words

---

vocab_list/models.py

quick fix so I'm merging without review as `dev` is currently broken

Cannot call make_lemma anymore as it's commented out

---

.github/workflows/ci.yaml
static/src/js/app/Vocab.vue
static/src/js/app/index.js

This fixes the issue with vocab lists not loading

Fix vocab list

---

static/src/js/app/modules/LatticeTree.vue
static/src/js/app/modules/LemmatizedText.vue
static/src/js/app/modules/Token.vue
static/src/scss/_config.scss

1. automatically mark as resolved when node is selected
2. add highlighting of identical forms
3. separate button for "apply all" (once you've disambiguated one)

Batch Lemma Disambiguation

---

hedera/api.py
hedera/urls.py
static/src/js/app/Vocab.vue
static/src/js/app/api.js
static/src/js/app/components/icons.js
static/src/js/app/components/vocab-list-table/VocabListEntryRow.vue
static/src/js/app/components/vocab-list-table/VocabListTable.vue

Here is the editing and deleting UI for a vocab list.  Still need to add the ability to add a single entry.

Add ability to edit/delete entries on vocab list

---

groups/templates/groups/group.html
groups/views.py
hedera/api.py
lemmatized_text/models.py
lemmatized_text/views.py
static/src/js/app/api.js
static/src/js/app/modules/LatticeTree.vue

Clones and redirects preserving prior lemmatization and disambiguation.
also added teacher/learner links for teacher:

Update Cloning Model

---

hedera/api.py
hedera/templates/vocab_list/list.html
static/src/js/app/App.vue
static/src/js/app/Vocab.vue
static/src/js/app/components/vocab-list-select/VocabListEntry.vue
static/src/js/app/components/vocab-list-select/VocabListSelect.vue
static/src/js/app/components/vocab-list-table/VocabListEntryRow.vue
static/src/js/app/components/vocab-list-table/VocabListTable.vue
vocab_list/models.py
vocab_list/views.py

Improve Vocab Lists

---

lemmatization/services/morpheus.py
logeion_load.py

Fixes #160 and other issues
Also adds some extra debugging output from the Logeion load

strip macrons on lemmatization

---

hedera/settings.py
hedera/templates/robots.txt
hedera/urls.py

Adds `robots.txt` allowing the SiteImprove link checker to crawl parts of the site. 
@bilbe @joshuagetega

Add robots.txt 

---

import-data/ivy_extra_latin_forms.tsv
lemmatization/models.py

* improved extra forms importation
* included Ivy's list

wonky words

---

hedera/templates/site_base.html

Added a dashboard nav link so user can navigate back to the dashboard view
Jira Story: [ATGU-3136](https://jira.huit.harvard.edu/browse/ATGU-3136)

add dashboard to navbar

---

.pre-commit-config.yaml
Pipfile
README.md
hedera/api.py

This is in reference to [ATGU-3130](https://jira.huit.harvard.edu/browse/ATGU-3130)
- Added pre-commit yaml file to run isort before commits
- Added eslint, flake8 and updated readme

Pre commit install

---

.pre-commit-config.yaml

Updated the `pre-commit-config.yaml` file to read config from `setup.cfg` file instead of from `args` attribute

added additional_dependencies for flake8-quotes

---

hedera/api.py
hedera/tests/test_api.py

Added json responses and updated tests to the following API's
- MeAPI
- LatticeNodesAPI
- PersonalVocabularyListAPI

Refactor http error responses

---

.github/workflows/ci.yaml
hedera/api.py
hedera/tests/test_api.py
hedera/urls.py

- Added supported languages endpoint
- Added test

added supported languages endpoint

---

.github/workflows/ci.yaml
README.md
package.json

Just adds JS tests to CI runs.

Run JS tests in CI

---

docker-compose-common.yml
docker-compose.yml

- added `webpack-stats` and `/static/src` to npm volume to fix webpack hot reloading
- added `webpack-stats` to django volume via `docker-compose-common.yml`

Fix webpack hot reloading

---

hedera/api.py
hedera/tests/test_api.py
hedera/tests/utils.py
lemmatized_text/models.py

- Created a method on the LemmatizedText model called `is_valid_user` to check if any of the these fields are true: `is_student` `is_teacher` `is_public` `is_created_by`. If any of these are true the function will return `True`
- Update the `TokeHistoryAPI class` to only return tokenHistory if the user is valid
Note: This only checks if the group id is associated with at least one of the classes the user is either `enrolled_classes` or `taught_classes`.

Added validation for student and teacher on LemmatizedText model

---

load_latin_form_to_lemma.py
load_latin_lemma.py

Fixes issue with the load script and the `count` variable.

Fix load script issue with count

---

hedera/supported_languages.py

This PR disables Greek, Russian, and Chinese in the UI for Version 1.0
We will have to enable them after Version 1.0 is released.

added comment for disabled languages

---

README.md
hedera/api.py
lemmatization/services/latin.py
load_latin_gloss.py
static/src/js/app/modules/FormDisambiguation.vue

This PR adds loading script to load in definitions into the `gloss` table
Note: there are some changes for words/normalized_words with capitalization e.g. `Sum` - would not be recognized as a lemma and would return no glosses.

add gloss loading script

---

load_latin_gloss.py

This PR updates `load_latin_gloss.py` script to improve the load time since it can take >10 mins to load a remote DB.
Notes:
- Replaced all database queries inside the loop with dict lookups. This produced a significant speed up and brought the load time to under a minute.
- The `all_gloss_data` dict lookup is intended to check if a gloss exists in the DB, which means we need the lemma ID as part of the lookup key.
- Only 16,340 (31%) of the 51,374 entries in `distinct_lemma_short_defs_frequencies.tsv` have associated glosses. Once loaded, the gloss table should have >= 16,340 glosses since a gloss may be used more than once. 
- After an initial load, the gloss table has 16,718 rows.

Update gloss loading script

---

vocab_list/models.py

Fix zero division when calculating `link_status`

fix vocab list not loading in text ui

---

import-data/shelmerdine_latin.tsv
lemmatization/admin.py
lemmatized_text/admin.py
load_latin_vocab.py
vocab_list/admin.py

It's just the one file but it's a new format: lemma, headword, definition, chapter.

Ivy's new improved list for Shelmerdine. --bb

---

split_vocab_spreadsheet_by_chapter.py

This just adds a script to split an input file based on a "chapter" field to output a set of vocab list spreadsheets for each chapter. Each vocab list has the vocab for that chapter and every chapter before it. The script should be invoked by 
```python split_vocab_spreadsheet_by_chapter.py path/to/spreadsheet.tsv```

Vocab split script

---

static/src/js/app/modules/FormDisambiguation.vue
vocab_list/admin.py

This is PR is a bug fix for the teacher view not displaying glosses for proper nouns.

fix glosses for proper nouns in teacher view

---

vocab_list/views.py

Minor fix to make sure that the personal vocab page has the title "Hedera | Personal Vocabulary List"

add page title to view context

---

hedera/api.py

This is from Artie's feedback from a previous PR (#445) where I didn't notice I hadn't saved the file before committing

fix API check for invalid language

---

static/src/js/app/Texts.vue

This PR fixes the lemmatized text list in the `Text vue` so all the lemmatized text are being populated correctly.

fix texts list ui

---

static/src/js/app/PersonalVocab.vue
static/src/js/app/Texts.vue
static/src/js/app/api.js
static/src/js/app/constants.js
static/src/js/app/vuex/actions.js
static/src/js/app/vuex/mutations.js
static/src/js/app/vuex/state.js
static/src/js/app/vuex/tests/mutations.spec.js
static/src/js/tests/VocabPersonal.spec.js

This PR is to fix the actions/mutations that are not working.
- Fixed issue with Learner view familiarity not updating correctly/duplicating entries in personal vocabulary view #473 
- Fixed issue with selecting a new gloss in lemmatized text view causing the text to disappear
- Added `LEMMATIZED_TEXT_FETCH_LIST ` action and mutation for global use
- Fixed/rename actions and mutations related to personal vocabulary list
- Fix payload names so mutations receive the correctly structured payloads
- Fix failing mutations, actions and Personal Vocab tests

Dojo 20221206

---

static/src/js/app/api.js

This PR fixes #501  the personal vocab lemma edit by fixing the endpoint where we retrieve the lemma list for the autocomplete feature.

Fix personal vocab lemma edit

---

hedera/api.py

This PR is from the dojo between me and @jaguillette(thanks to Jeremy for cracking the code/django docs on this) which reduces the number of database queries that `PartialMatchFormLookupAPI` makes. Fixes #507 
- The endpoint has been refactored to `filter`/`distinct`/`order_by`(rank) on the `Lemma` model based on the `forms__form` parameter via the  reverse relation from the `FormToLemma` model through the `related_name` attribute.
- `prefetch_related` has been implemented to retrieve the `glosses` associated with each of the lemma which drastically reduces the number of queries from over `9000` to `1`

Fix number of database queries from dojo

---

static/src/js/app/components/TextRow.vue

This PR fixes the progress bar indicator when submitting text to be lemmatized.
- Changed the names of the API functions to match up to the newly formatted names

fix progress bar for text lemmatizer

---

hedera/api.py
hedera/tests/test_api.py
hedera/urls.py
static/src/js/app/PersonalVocab.vue
static/src/js/app/api.js
static/src/js/app/constants.js
static/src/js/app/index.js
static/src/js/app/vuex/actions.js
static/src/js/app/vuex/mutations.js
static/src/js/app/vuex/state.js

This PR fixes the lemma edit functionality so that lemmas with numbers attached can be use in the personal vocab editor.

Fix lemma edit

---

static/src/js/app/components/TextRow.vue

This PR adds a transition between progress bar status updates so that it looks smooth instead of jumping between completion states.
Thanks @Tanvez @jaguillette @bilbe (dojo style)!

Animate lemmatization progress bar
